# NumPy

ar


In [5]:
import numpy as np
arr = np.array([1,2,3])
arr


array([1, 2, 3])

In [7]:
arr1= np.arange(10);
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr=np.arange(0,2,0.2);
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [14]:
arr=np.random.randint(10,size=(3,5));
arr

array([[9, 9, 7, 5, 7],
       [0, 1, 1, 0, 3],
       [8, 0, 2, 0, 7]], dtype=int32)

In [16]:
arr.shape

(3, 5)

In [18]:
arr_sum=np.sum(arr,axis=0)
print(arr_sum)

[17 10 10  5 17]


In [22]:
arr=np.arange(10,60,10)
arr

array([10, 20, 30, 40, 50])

In [29]:
arr2=np.arange(1,10,1).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
arr=np.arange(0,1,0.2)
arr

array([0. , 0.2, 0.4, 0.6, 0.8])