In [2]:
a=1


### 특성(Feature) 공학과 규제(Regularization : 정형화)

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("../Data/fish.csv")
df.head()

,length,height,width
0,8.4,2.11,1.41
1,13.7,3.53,2.00
2,15.0,3.82,2.43
3,16.2,4.59,2.63
4,17.4,4.59,2.94


In [5]:
fish_full=df.to_numpy()
fish_full[:5]

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94]])

In [7]:

df=pd.read_csv("../Data/fish_weight.csv")
df.head()

,weight
0,5.9
1,32.0
2,40.0
3,51.5
4,70.0


In [8]:
fish_weight=df.to_numpy()
fish_weight[:5]

array([[ 5.9],
       [32. ],
       [40. ],
       [51.5],
       [70. ]])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_input,test_input,train_target,test_target= \
    train_test_split(
        fish_full,
        fish_weight,
        random_state=42
    )

ValueError: At least one array required as input

In [12]:
from sklearn.preprocessing import PolynomialFeatures

In [14]:
poly = PolynomialFeatures()
poly.fit([[2,3]])
poly.transform([[2,3]])

array([[1., 2., 3., 4., 6., 9.]])

In [15]:
df=pd.read_csv("../Data/fishes.csv")
df.head()

,Species,Weight,Length,Diagonal,Height,Width
0,Bream,242.0,25.4,30.0,11.5200,4.0200
1,Bream,290.0,26.3,31.2,12.4800,4.3056
2,Bream,340.0,26.5,31.1,12.3778,4.6961
3,Bream,363.0,29.0,33.5,12.7300,4.4555
4,Bream,430.0,29.0,34.0,12.4440,5.1340


In [16]:
fishes=df.to_numpy()
fishes[:5]

array([['Bream', 242.0, 25.4, 30.0, 11.52, 4.02],
       ['Bream', 290.0, 26.3, 31.2, 12.48, 4.3056],
       ['Bream', 340.0, 26.5, 31.1, 12.3778, 4.6961],
       ['Bream', 363.0, 29.0, 33.5, 12.73, 4.4555],
       ['Bream', 430.0, 29.0, 34.0, 12.444, 5.134]], dtype=object)

In [ ]:
train_input,test_input,train_target,test_target= \
    train_test_split(
        fishes_full,
        fishes_weight,
        random_state=42
    )